install.packages("DBI")
install.packages("RPostgres")
install.packages("dplyr")
install.packages("plyr")
install.packages("sf")
install.packages("tidyverse")
install.packages("ggplot2")
install.packages("treemapify")
install.packages("viridis")
install.packages("RCurl")
install.packages("lubridate")
install.packages("janitor")
install.packages("kableExtra")
install.packages("knitr")
install.packages("tinytex")
install.packages("rmarkdown", type = "source")

library(tinytex)

install_tinytex()